In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [2]:
wikidiz_file = "WikiDisney.csv"
wikidiz_df = pd.read_csv(wikidiz_file)
wikidiz_df.head(25)

   Type of Film                           Title          US Release
0             L                      Toby Tyler    January 21, 1960
1             L                       Kidnapped   February 24, 1960
2             L                       Pollyanna        May 19, 1960
3             L               The Sign of Zorro       June 11, 1960
4             N                      Jungle Cat     August 10, 1960
5             L                   Ten Who Dared    November 1, 1960
6             L           Swiss Family Robinson   December 21, 1960
7             A  One Hundred and One Dalmatians    January 25, 1961
8             L     The Absent-Minded Professor      March 16, 1961
9             L                 The Parent Trap       June 21, 1961
10            L    Nikki, Wild Dog of the North       July 12, 1961
11            L                Greyfriars Bobby       July 17, 1961
12            L                Babes in Toyland   December 14, 1961
13            L                      Moon Pilot       April 5, 1962
14            L                     Bon Voyage!        May 17, 1962
15            L                         Big Red        June 6, 1962
16            L                   Almost Angels  September 26, 1962
17            L              The Legend of Lobo    November 7, 1962
18            L      In Search of the Castaways   December 21, 1962
19            L                  Son of Flubber    January 16, 1963
20            L  Miracle of the White Stallions      March 29, 1963
21            L                      Savage Sam        June 1, 1963
22            L                    Summer Magic        July 7, 1963
23            L          The Incredible Journey   November 20, 1963
24            A          The Sword in the Stone   December 25, 1963

In [3]:
listdiz_file = "disneylist.csv"
listdiz_df = pd.read_csv(listdiz_file)
listdiz_df.head(25)

                                          TITLE     YEAR
0                       Pinocchio (Live-Action)  Unknown
1                                  Kim Possible      TBA
2                                        TRON 3  Stalled
3                                   Enchanted 2      DEV
4                                          Tink      DEV
5                                      Gigantic     2020
6                                 Jungle Cruise     2020
7                                      Frozen 2     2019
8                           Dumbo (Live-Action)     2019
9                                 Descendants 3     2019
10                          Mulan (Live-Action)     2019
11                                  Toy Story 4     2019
12                                The Lion King     2019
13                                      Aladdin     2019
14                         Mary Poppins Returns     2018
15                                   Magic Camp     2018
16                        Cruella (Live-Action)     2018
17  Wreck-It Ralph 2: Ralph Breaks the Internet     2018
18                                Freaky Friday     2018
19                            A Wrinkle in Time     2018
20                                      Zombies     2018
21                                Incredibles 2     2018
22                                       Cars 3     2017
23                         Beauty and the Beast     2017
24                                         Coco     2017

In [4]:
imdbdiz_file = "CSV's_IMDBDisney.csv"
imdbdiz_df = pd.read_csv(imdbdiz_file)
imdbdiz_df.head(25)

FileNotFoundError: File b"CSV's_IMDBDisney.csv" does not exist

In [ ]:
grossdiz_file = "Movies_Gross_Sales.csv"
grossdiz_df = pd.read_csv(grossdiz_file)
grossdiz_df.head(25)

In [ ]:
chardiz_file = "disney-characters.csv"
chardiz_df = pd.read_csv(chardiz_file)
chardiz_df.head(25)

In [ ]:
voiceactdiz_file = "disney_voice_actors.csv"
voiceactdiz_df = pd.read_csv(voiceactdiz_file)
voiceactdiz_df.head(25)

In [ ]:
connection_string = "root:7Beetaz!@127.0.0.1/disney"
engine = create_engine(f'mysql://{connection_string}')

In [ ]:
engine.table_names()

In [ ]:
# Send the Wikipedia Disney data to SQL
wikidiz_df.to_sql(name='wikidisney', con=engine, if_exists='append', index=False)

In [ ]:
# Send the Disney List data to SQL
listdiz_df.to_sql(name='disneylist', con=engine, if_exists='append', index=False)

In [ ]:
# Send the IMDB Disney data to SQL
imdbdiz_df.to_sql(name='imdbdisney', con=engine, if_exists='append', index=False)

In [ ]:
# Send the Gross Movie Sales data to SQL
grossdiz_df.to_sql(name='grossdisney', con=engine, if_exists='append', index=False)

In [ ]:
# # Send the Disney Character data to SQL
# chardiz_df.to_sql(name='chardiz_new', con=engine, if_exists='append', index=False)

In [ ]:
# # Send the Disney Voice Actor data to SQL
# voiceactdiz_df.to_sql(name='voiceactdiz_new', con=engine, if_exists='append', index=False)